/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const Layout1AboutLazyImport = createFileRoute('/layout1/about')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const Layout1AboutLazyRoute = Layout1AboutLazyImport.update({
  path: '/layout1/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/layout1/about.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/layout1/about': {
      id: '/layout1/about'
      path: '/layout1/about'
      fullPath: '/layout1/about'
      preLoaderRoute: typeof Layout1AboutLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  Layout1AboutLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/layout1/about"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/layout1/about": {
      "filePath": "layout1/about.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
